name: release

on:
  push:
    tags:
     - "v*"

jobs:
  release:
    name: "Release"
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1.0

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.1.0

    - name: Restore NuGet packages
      run: |
        cd Magitek
        nuget restore Magitek.sln

    - name: Extract version from tag
      id: extract_version
      run: |
        $version="${{ github.ref_name }}"
        $version="${version#v}"
        echo "VERSION=$version.0" >> $env:GITHUB_ENV

    - name: Verify version string
      run: echo "Version is $env:VERSION"

    - name: Update AssemblyInfo
      run: |
        $version = $env:VERSION
        Write-Host "Updating AssemblyInfo.cs with version $version"
        $assemblyInfoPath = "Magitek/Properties/AssemblyInfo.cs"
        (Get-Content $assemblyInfoPath) -replace '(\[assembly: AssemblyVersion\(")[^"]*("\)\])', "[assembly: AssemblyVersion(`"$version`")]" | Set-Content $assemblyInfoPath
        (Get-Content $assemblyInfoPath) -replace '(\[assembly: AssemblyFileVersion\(")[^"]*("\)\])', "[assembly: AssemblyFileVersion(`"$version`")]" | Set-Content $assemblyInfoPath

    - name: Verify AssemblyInfo
      run: |
        Write-Host "Contents of AssemblyInfo.cs after replacement:"
        Get-Content "Magitek/Properties/AssemblyInfo.cs"

    - name: Build solution
      run: |
        cd Magitek
        msbuild Magitek.sln /p:Configuration=Release

    - name: Generate Version.txt
      run: echo "${{ github.ref_name }}" > ./Magitek/bin/release/Version.txt

    - name: Create Magitek.zip
      run: |
        powershell Compress-Archive -Path ./Magitek/bin/release/Magitek.dll, ./Magitek/bin/release/Version.txt, ./MagitekLoader/MagitekLoader.cs -DestinationPath ./Magitek/bin/release/Magitek.zip

    - name: Upload Artifacts for Release
      uses: actions/upload-artifact@v4
      with:
        name: Magitek.zip
        path: ./Magitek/bin/release/Magitek.zip

    - name: Upload Version.txt for Release
      uses: actions/upload-artifact@v4
      with:
        name: Version.txt
        path: ./Magitek/bin/release/Version.txt

    - name: Create GitHub Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          ./Magitek/bin/release/Magitek.zip
          ./Magitek/bin/release/Version.txt
